import "./globals.css"
import { UiProvider } from "./providers/UiProvider"
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body>
        <UiProvider>
          {children}
        </UiProvider>
      </body>
    </html>
  )
}
